[package]
name = "quick-xml"
version = "0.1.4"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
description = "High performance xml reader and writer"

documentation = "http://tafia.github.io/quick-xml/quick_xml/index.html"
repository = "https://github.com/tafia/quick-xml"

readme = "README.md"
keywords = ["xml", "reader", "parser", "write"]
license = "MIT"

[dependencies]
log="0.3"
