[package]
name = "quick-xml"
version = "0.1.7"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
description = "High performance xml reader and writer"

documentation = "http://tafia.github.io/quick-xml/quick_xml/index.html"
repository = "https://github.com/tafia/quick-xml"

readme = "README.md"
keywords = ["xml", "reader", "parser", "write"]
license = "MIT"

[dependencies]
log = "0.3"

[dev-dependencies]
xml-rs = "0.3.0"

[lib]
bench = false

[profile.bench]
opt-level = 3
debug = true
rpath = false
lto = false
debug-assertions = false
codegen-units = 1
