[package]
name = "quick-xml"
version = "0.4.2"
authors = ["Johann Tuffe <tafia973@gmail.com>"]
description = "High performance xml reader and writer"

documentation = "https://docs.rs/quick-xml"
repository = "https://github.com/tafia/quick-xml"

readme = "README.md"
keywords = ["xml", "reader", "parser", "writer"]
license = "MIT"

[dependencies]
log = "0.3.6"

[dev-dependencies]
xml-rs = "0.3.4"

[lib]
bench = false
