name: Rust

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build
    - name: Run tests no features
      run: cargo test --no-default-features
    - name: Run tests all-features
      run: cargo test --all-features
    - name: Check fmt
      run: cargo fmt -- --check

